### ISSUE TITLE
notify handler with import_tasks or block not work

### ISSUE THREAD

**Issue by asapdotid** [asapdotid/ansible-role-minio#1]
##### SUMMARY
notify inside import_tasks not work

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.11.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/asap/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/asap/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True
```

##### OS / ENVIRONMENT

Manjaro 21.1.1

##### STEPS TO REPRODUCE

```yaml
- name: SSL preparation
  include_tasks: "ssl/{{ ansible_system }}.yml"
  when:
    - minio_enable_ssl
  notify: Restart Minio
```

##### ACTUAL RESULTS

```

```
